{
  "status": "active", 
  "unique_views": 184, 
  "request_instructor_me": false, 
  "change_log": [
    {
      "type": "create", 
      "anon": "stud", 
      "when": "2017-10-01T18:18:30Z", 
      "data": "j892kzbfcq24gk"
    }, 
    {
      "type": "update", 
      "anon": "no", 
      "when": "2017-10-01T18:22:00Z", 
      "data": "j892pheo2q74f3", 
      "uid": "i4ket0u1z5q31a"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T18:26:40Z", 
      "type": "followup", 
      "uid": "i4ket0u1z5q31a"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T18:45:34Z", 
      "type": "feedback", 
      "uid": "i4ket0u1z5q31a"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T19:25:16Z", 
      "type": "feedback", 
      "uid": "gns9oa0pgsO"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T19:57:27Z", 
      "type": "followup", 
      "uid": "hklp7yk0n6o2j8"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T20:13:16Z", 
      "type": "feedback", 
      "uid": "gns9oa0pgsO"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T20:48:59Z", 
      "type": "feedback", 
      "uid": "gns9oa0pgsO"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-01T23:20:37Z", 
      "type": "feedback", 
      "uid": "ijawwe19w053cm"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-02T02:30:34Z", 
      "type": "followup", 
      "uid": "hyzorpzxos76lk"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-02T03:02:28Z", 
      "type": "feedback", 
      "uid": "i4ket0u1z5q31a"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-02T03:03:17Z", 
      "type": "feedback", 
      "uid": "i4ket0u1z5q31a"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-02T03:12:03Z", 
      "type": "feedback", 
      "uid": "i4ket0u1z5q31a"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-02T19:09:13Z", 
      "type": "feedback", 
      "uid": "hklp7yk0n6o2j8"
    }, 
    {
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "when": "2017-10-02T19:37:59Z", 
      "type": "feedback", 
      "uid": "i4nkipeofrkrz"
    }, 
    {
      "uid": "i4hdvab632i522", 
      "type": "s_answer", 
      "when": "2017-10-06T08:06:53Z", 
      "to": "j892kzbdmup4gj", 
      "anon": "no", 
      "data": "j8flxpnkzy1ra"
    }
  ], 
  "upvote_ids": [], 
  "id": "j892kzbdmup4gj", 
  "bookmarked": 7, 
  "no_answer": 0, 
  "i_edits": [], 
  "is_bookmarked": false, 
  "children": [
    {
      "folders": [], 
      "updated": "2017-10-01T18:26:40Z", 
      "no_upvotes": 0, 
      "uid": "i4ket0u1z5q31a", 
      "created": "2017-10-01T18:26:40Z", 
      "type": "followup", 
      "no_answer": 0, 
      "id": "j892vh9s26zps", 
      "anon": "no", 
      "bucket_name": "This week", 
      "config": {}, 
      "bucket_order": 4, 
      "data": {
        "embed_links": null
      }, 
      "children": [
        {
          "folders": [], 
          "updated": "2017-10-01T18:45:34Z", 
          "uid": "i4ket0u1z5q31a", 
          "created": "2017-10-01T18:45:34Z", 
          "type": "feedback", 
          "id": "j893jsz6bs13p3", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>It is definitely generating an overflow:</p>\n<pre>RuntimeWarning: overflow encountered in long_scalars</pre>\n<p>One of the sums\u00a0comes out as\u00a0-2147169382.</p>\n<p>But supposedly I am running a 64 bit version of Python:</p>\n<pre>Python 2.7.13 :: Anaconda 4.3.0 (64-bit)</pre>\n<p>So why am I getting 32 bit signed overflow errors?</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-01T19:25:16Z", 
          "uid": "gns9oa0pgsO", 
          "created": "2017-10-01T19:25:16Z", 
          "type": "feedback", 
          "id": "j894yup2a0d50i", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>just comment the line where the seed is set in both hash type&#39;s ctors out.</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-01T23:20:37Z", 
          "uid": "ijawwe19w053cm", 
          "created": "2017-10-01T23:20:37Z", 
          "type": "feedback", 
          "id": "j89ddi8olpq2na", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>which line?</p>\n<p></p>\n<p>I cast the int to long and there&#39;s no more overflow issue</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-02T03:02:28Z", 
          "uid": "i4ket0u1z5q31a", 
          "created": "2017-10-02T03:02:28Z", 
          "type": "feedback", 
          "id": "j89lasyjhf51s", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>I tried that and it worked: long(seed)</p>"
        }
      ], 
      "subject": "<p>This doesn&#39;t make sense, am I getting a signed value that overflows because seed expects an unsigned value?</p>\n<p>The max value in the input file is\u00a02147483173 and that won&#39;t overflow 4294967295 when added to\u00a01494572667 unless it is wrapping for a signed value.</p>"
    }, 
    {
      "folders": [], 
      "updated": "2017-10-01T19:57:27Z", 
      "no_upvotes": 0, 
      "uid": "hklp7yk0n6o2j8", 
      "created": "2017-10-01T19:57:27Z", 
      "type": "followup", 
      "no_answer": 0, 
      "id": "j89648n3ym125u", 
      "anon": "no", 
      "bucket_name": "This week", 
      "config": {}, 
      "bucket_order": 4, 
      "data": {
        "embed_links": null
      }, 
      "children": [
        {
          "folders": [], 
          "updated": "2017-10-01T20:13:16Z", 
          "uid": "gns9oa0pgsO", 
          "created": "2017-10-01T20:13:16Z", 
          "type": "feedback", 
          "id": "j896oktx1zs3co", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>or better yet, don&#39;t put your arithmetic within the numpy function call.\u00a0</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-01T20:48:59Z", 
          "uid": "gns9oa0pgsO", 
          "created": "2017-10-01T20:48:59Z", 
          "type": "feedback", 
          "id": "j897yianpgw21f", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>btw, thanks for sharing this gene, i wasn&#39;t aware that this happened with numpy.</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-02T19:09:13Z", 
          "uid": "hklp7yk0n6o2j8", 
          "created": "2017-10-02T19:09:13Z", 
          "type": "feedback", 
          "id": "j8aju275dwg77g", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>Actually if you add an int and an int32 outside the numpy function call it&#39;ll still overflow unless you cast the int32 to an int. At least that&#39;s what happened in my experience.\u00a0</p>\n<p></p>\n<p>No problem! I spent a few frustrating hours tackling this... thought it might be helpful for others</p>"
        }
      ], 
      "subject": "<p>Also in case it helps anyone, I was having this problem and it turns out that numpy\u00a0ints will overflow while the standard python ints will not. And since we&#39;re using numpy&#39;s randint() function, you&#39;re going to be dealing with a mixture of both. I recommend casting everything to the standard int to avoid this.\u00a0</p>"
    }, 
    {
      "folders": [], 
      "updated": "2017-10-02T02:30:34Z", 
      "no_upvotes": 0, 
      "uid": "hyzorpzxos76lk", 
      "created": "2017-10-02T02:30:34Z", 
      "type": "followup", 
      "no_answer": 0, 
      "id": "j89k5s4jxt47l", 
      "anon": "no", 
      "bucket_name": "This week", 
      "config": {}, 
      "bucket_order": 4, 
      "data": {
        "embed_links": null
      }, 
      "children": [
        {
          "folders": [], 
          "updated": "2017-10-02T03:03:17Z", 
          "uid": "i4ket0u1z5q31a", 
          "created": "2017-10-02T03:03:17Z", 
          "type": "feedback", 
          "id": "j89lbv0op2v6bo", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>What happens if you cast as long(...)?</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-02T03:12:03Z", 
          "uid": "i4ket0u1z5q31a", 
          "created": "2017-10-02T03:12:03Z", 
          "type": "feedback", 
          "id": "j89ln4p2ksf1ln", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>P.S. I would recommend using the built in Python types rather than numpy types since the only thing we are allowed to import out of numpy is random.</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-10-02T19:37:59Z", 
          "uid": "i4nkipeofrkrz", 
          "created": "2017-10-02T19:37:59Z", 
          "type": "feedback", 
          "id": "j8akv1uzj4olh", 
          "anon": "no", 
          "bucket_name": "This week", 
          "config": {}, 
          "bucket_order": 4, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>Are you computing the median in your code? I&#39;m using the median functionality provided by NumPy, but since this is for Task 3, I will probably remove the code to avoid any conflicts.</p>\n<p></p>\n<p>\u00a0</p>"
        }
      ], 
      "subject": "<p>I have 32 bit python installed on my system.\u00a0 May I use the the numpy.uint32 function to cast the numbers so the random.randint() can run without throwing &#34;ValueError: object of too small depth for desired array&#34;\u00a0</p>"
    }, 
    {
      "folders": [], 
      "is_tag_endorse": false, 
      "created": "2017-10-06T08:06:53Z", 
      "type": "s_answer", 
      "tag_endorse_arr": [], 
      "id": "j8flxpnguwo1r9", 
      "bucket_name": "Today", 
      "config": {}, 
      "tag_endorse": [], 
      "bucket_order": 2, 
      "data": {
        "embed_links": []
      }, 
      "children": [], 
      "history": [
        {
          "content": "Marking as resolved; see followups", 
          "anon": "no", 
          "created": "2017-10-06T08:06:53Z", 
          "uid": "i4hdvab632i522", 
          "subject": ""
        }
      ]
    }
  ], 
  "nr": 511, 
  "bucket_order": 2, 
  "type": "question", 
  "folders": [
    "project"
  ], 
  "no_answer_followup": 0, 
  "num_favorites": 4, 
  "bucket_name": "Today", 
  "q_edits": [], 
  "data": {
    "embed_links": []
  }, 
  "request_instructor": 0, 
  "tags": [
    "project", 
    "student"
  ], 
  "created": "2017-10-01T18:18:30Z", 
  "is_tag_good": false, 
  "config": {}, 
  "s_edits": [], 
  "my_favorite": false, 
  "default_anonymity": "no", 
  "t": 1509145198677, 
  "tag_good": [], 
  "tag_good_arr": [], 
  "history": [
    {
      "content": "<p>In office hours it was suggested that we set the following to get a time based seed:</p>\n<pre>configData[&#39;genSeed&#39;] = None</pre>\n<p>The generates values like\u00a01494572667 for the random time seed in bfProjectUtils.py.</p>\n<p>However, I now get the below error when calling random.seed:</p>\n<pre>ValueError: Seed must be between 0 and 4294967295</pre>\n<p>Is the appropriate fix to mod (seed &#43; x) or to force seed to be smaller?</p>", 
      "anon": "no", 
      "created": "2017-10-01T18:22:00Z", 
      "uid": "i4ket0u1z5q31a", 
      "subject": "ValueError: Seed must be between 0 and 4294967295"
    }, 
    {
      "content": "<p>In office hours it was suggested that we set the following to get a time based seed:</p>\n<pre>configData[&#39;genSeed&#39;] = None</pre>\n<p>The generates values like\u00a01494572667 for the random time seed in bfProjectUtils.py.</p>\n<p>However, I now get the below error when calling random.seed:</p>\n<pre>ValueError: Seed must be between 0 and 4294967295</pre>\n<p>Is the appropriate fix to mod (seed &#43; x) or to force seed to be smaller?</p>", 
      "anon": "stud", 
      "created": "2017-10-01T18:18:30Z", 
      "subject": "ValueError: Seed must be between 0 and 4294967295"
    }
  ]
}